config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'admin'
  end



  mount Sidekiq::Web, at: '/sidekiq'

  resources :filiais

  get 'demais_racs/index'

  resources :helpers

  resources :demais_racs do
    member do
      get :atualizar
    end
  end

  resources :grp_consensadores
  resources :grp_homologadores

  resources :followups

  resources :documento_localizacoes

  get 'anexo_documentos/new'

  get 'anexo_documentos/create'

  get 'anexo_documentos/anexo_params'

  resources :anexo_docs

  resources :consensadores

  resources :homologadores

  resources :consensamentos

  resources :documentos do
    member do

      get :novo



    end
  end

  get 'anexo_reunioes/new'

  get 'anexo_reunioes/create'

  resources :topicos

  resources :locais

  resources :raps do
    member do
      get :atualizar
      get :alterar_data_acao
    end
  end

  resources :racs do
    member do
      get :atualizar
      get :alterar_data_acao
    end
  end

  resources :rais do
    member do
      get :atualizar
    end
  end

  resources :reunioes do
    member do
      get :atualizar
    end
  end

  resources :planosauditorias do
    member do
      get :atualizar
    end
  end

  resources :funcionarios

  get 'grupos/index'

  resources :tipo_racs do
    member do
      get :atualizar
    end
  end



  resources :tipo_docs do
    member do
      get :atualizar
    end
  end

  resources :tipo_ncs do
    member do
      get :atualizar
    end
  end

  resources :areas do
    member do
      get :atualizar
    end
  end

  resources :pastas do
    member do
      get :atualizar
    end
  end  

  resources :numeros do
    member do
      get :atualizar
    end
  end  

  resources :localizacoes do
    member do
      get :atualizar
    end
  end  

  resources :tipo_atas do
    member do
      get :atualizar
    end
  end

  resources :funcionarios do
    member do
      get :atualizar
    end
  end

  resources :auditorias do
    member do
      get :atualizar
      get :imprimir
      get :visualizar
    end
  end

  resource :anexo_reunioes do
    member do
      get :salvar
    end
  end

  get 'notificacoes/visto'

  get 'notificacoes/listar'

  get 'sessions/create'
  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'sair', to: 'sessions#destroy', as: 'signout'
  get 'sessions/nao_autorizado'

  get 'home/index'
  get 'notificacoes/pesquisar'

  match 'ajax_planos', controller: 'planosauditorias', action: 'ajax_planos', via: 'get'
  match 'ajax_ajuda', controller: 'helpers', action: 'ajax_ajuda', via: 'get'

  match 'editar-grupo-consenso-:id', controller: 'grp_consensadores', action: 'edit', via: 'get'
  match 'editar-grupo-consenso', controller: 'grp_consensadores', action: 'update', via: 'post'
  match 'editar-grupo-consenso', controller: 'grp_consensadores', action: 'update', via: 'patch'

  match 'editar-grupo-homologacao-:id', controller: 'grp_homologadores', action: 'edit', via: 'get'
  match 'editar-grupo-homologacao', controller: 'grp_homologadores', action: 'update', via: 'post'
  match 'editar-grupo-homologacao', controller: 'grp_homologadores', action: 'update', via: 'patch'

  match 'visualizar-documentos-:filtro', controller: 'documentos', action: 'index', via: 'get'
  match 'imprimir-rac-:id', controller: 'racs', action: 'print', via: 'get'
  match 'imprimir-rai-:id', controller: 'rais', action: 'print', via: 'get'
  match 'imprimir-rap-:id', controller: 'raps', action: 'print', via: 'get'
  match 'imprimir-demais-rac-:id', controller: 'demais_racs', action: 'print', via: 'get'
  match 'visualizar-documento-:id', controller: 'documentos', action: 'visualizar', via: 'get'
  match 'documentos-excluidos', controller: 'documentos', action: 'lixeira', via: 'get'
  match 'consenso-documento-:id', controller: 'documentos', action: 'visualizar_via_email', via: 'get'

  match 'racs', controller: 'racs', action: 'index', via: 'get'


  match 'racs,visualizar,:filtro', controller: 'racs', action: 'lista', via: 'get'

  match 'enviar-doc-lixeira', controller: 'documentos', action: 'enviar_lixeira', via: 'post'
  match 'restaurar-doc-lixeira', controller: 'documentos', action: 'restaurar_lixeira', via: 'post'

  match 'demais-racs', controller: 'demais_racs', action: 'index', via: 'get'
  match 'inserir-demais-racs', controller: 'demais_racs', action: 'inserir', via: 'get'
  match 'raps', controller: 'raps', action: 'lista', via: 'get'

  match 'backup', controller: 'backup', action: 'do', via: 'get'

  match 'lista-auditorias-:id', controller: 'auditorias', action: 'lista', via: 'get'
  match 'visualizar-auditoria-:id', controller: 'auditorias', action: 'show', via: 'get'
  match 'download-anexo-:id', controller: 'reunioes', action: 'download_anexo', via: 'get'
  match 'doc-download-anexo-:id', controller: 'documentos', action: 'download_anexo', via: 'get'
  match 'visualizar-notificacao-:id', controller: 'notificacoes', action: 'visualizar', via: 'get'
  match 'anexar-arquivo-na-reuniao-:id', controller: 'reunioes', action: 'anexar', via: 'get'
  match 'adicionar-anexo-doc-:doc_id', controller: 'documentos', action: 'anexar', via: 'get'


  match 'adiamentos,rac,:id', controller: 'racs', action: 'ver_adiamentos', via: 'get'
  match 'gerenciar-ajuda', controller: 'helpers', action: 'index', via: 'get'

  match 'lista-de-racs', controller: 'racs', action: 'index', via: 'get'

  get 'ajax-salva-topico/:reuniao_id/:descricao', controller: 'reunioes', action: 'salva_topico', via: 'get'
  get 'encerrar-reuniao-:id', controller: 'reunioes', action: 'encerrar_reuniao', via: 'get'

  match 'relatorios-de-auditorias-internas', controller: 'rais', action: 'index', via: 'get'

  match 'auditorias,plano,:id', controller: 'auditorias', action: 'index', via: 'get'

  match 'marcar,como,finalizada,:id', controller: 'reunioes', action: 'marcar_finalizada', via: 'get'
  match 'excluir,topico,:id', controller:'reunioes', action: 'excluir_topico', via: 'get'

  match 'areas-de-atuacao', controller: 'areas', action: 'index', via: 'get'
  match 'ver-notificacoes', controller: 'notificacoes', action: 'listar', via: 'get'
  match 'tipos-de-atas', controller: 'tipo_atas', action: 'index', via: 'get'
  match 'tipos-de-ncs', controller: 'tipo_ncs', action: 'index', via: 'get'
  match 'tipos-de-docs', controller: 'tipo_docs', action: 'index', via: 'get'
  match 'tipos-de-racs', controller: 'tipo_racs', action: 'index', via: 'get'

  match 'planos-de-auditorias', controller: 'planosauditorias', action: 'index', via: 'get'

  match 'reunioes', controller: 'reunioes', action: 'index', via: 'get'

  match 'nova-reuniao', controller: 'reunioes', action: 'incluir', via: 'get'

  match 'rqa', controller: 'rqas', action: 'incluir', via: 'get'

  match 'lista-de-funcionarios', controller: 'funcionarios', action: 'index', via: 'get'
  match 'lista-de-funcionarios-2', controller: 'funcionarios', action: 'lista_funcionarios', via: 'get'

  match 'grupos-de-usuarios', controller: 'grupos', action: 'index', via: 'get'

  match 'cadastrar-nova-rai', controller: 'rais', action: 'new', via: 'get'
  match 'cadastrar-nova-rac', controller: 'racs', action: 'new', via: 'get'
  match 'cadastrar-nova-rap', controller: 'raps', action: 'new', via: 'get'
  match 'elaborar-documento', controller: 'documentos', action: 'new', via: 'get'


  match 'lista-de-raps', controller: 'raps', action: 'index', via: 'get'
  match 'ajax-lista-auditorias-:id', controller: 'auditorias', action: 'lista', via: 'get'
  match 'ajax-novo-topico-:reuniao_id', controller: 'topicos', action: 'add', via: 'get'

  match 'destinatarios-do-plano-auditoria,:id', controller: 'planosauditorias', action: 'destinatarios', via: 'get'
  match 'notificar-destinatarios-do-plano,:id', controller: 'planosauditorias', action: 'notificar_destinatarios', via: 'get'
  match 'apagar,auditoria,:id', controller: 'auditorias', action: 'delete', via: 'get'

  match 'grupo-consensadores', controller: 'grp_consensadores', action: 'index', via: 'get'
  match 'grupo-homologadores', controller: 'grp_homologadores', action: 'index', via: 'get'

  match 'iniciar-workflow-:id', controller: 'documentos', action: 'consensar', via: 'get'
  match 'enviar-para-consenso-:id', controller: 'documentos', action: 'enviar_consenso', via: 'get'

  post 'recebe-resposta-consenso', controller: 'documentos', action: 'recebe_resposta_consenso', via: 'post'
  get 'rqas', controller: 'rqas', action: 'index', via: 'get'
  post 'salva-rqa', controller: 'rqas', action: 'salvar', via: 'post'

  get 'confirmar-consenso-:id', controller: 'documentos', action: 'recebe_resposta_consenso', via: 'get'

  get 'homologar-documento-:id', controller: 'documentos', action: 'homologar', via: 'get'

  post 'recebe-resposta-homologacao', controller: 'documentos', action: 'recebe_resposta_homologacao', via: 'post'

  get 'confirmar-homologacao-:id', controller: 'documentos', action: 'recebe_resposta_homologacao', via: 'get'

  get 'add-atv-auditoria-:id', controller: 'auditorias', action: 'add_atividade', via: 'get'
  get 'del-atv-:id', controller: 'auditorias', action: 'del_atividade', via: 'get'

  post 'salva-atividade', controller: 'auditorias', action: 'salva_atividade', via: 'post'

  get 'follow-up-auditoria-:id', controller: 'followups', action: 'new', via: 'post'

  post '/tinymce_assets' => 'uploadimg#create'

  get 'atualizar-documento-:id', controller: 'documentos', action: 'edit', via: 'post'


  get 'adicionar-localizacao-doc-:id', controller: 'documento_localizacoes', action: 'new', via: 'get'

  get 'add-destinatarios', controller: 'followups', action: 'add_destinatario', via: 'post'

  get 'disparar-followup-:id', controller: 'auditorias', action: 'disparar_followup', via: 'post'

app/controllers/planosauditorias_controller.rb
class PlanosauditoriasController < ApplicationController
  before_action :set_planoauditoria, only: [:show, :edit, :update, :destroy, :atualizar]
  layout false, only: :ajax_planos
  before_filter :require_user

  def ajax_planos
    @planos = Planoauditoria.includes(:auditorias).order(:nome)
  end

  def destinatarios
    @auditoria = Planoauditoria.find params[:id]
    @usuarios = @auditoria.usuarios
    @ids = []

    @usuarios.each do |u|
      @ids << u.id
    end

    @usuarios = Usuario.where.not(id: @ids)

    NotificacaoMailer.msg(nil).deliver
  end

  def notificar_destinatarios
    if params[:id_plano].present?
      plano = Planoauditoria.find params[:id_plano]
      plano.usuarios.each do |u|
        NotificacaoMailer.msg(u.email).deliver
      end
    end
  end


  def index
    @planosauditorias = Planoauditoria.all.order("created_at desc")
    @plano = Planoauditoria.new
    @funcionarios = Funcionario.ativos
  end

  def atualizar
    @funcionarios = Funcionario.ativos
  end

  def show
  end

  def new
    @planoauditoria = Planoauditoria.new
  end

  def edit
  end

  def create
    @planoauditoria = Planoauditoria.new(planoauditoria_params)
    if @planoauditoria.save
      redirect_to planos_de_auditorias_path, notice: 'Plano de auditoria salvo com sucesso'
    else
      render :new
    end
  end


  def update
    if @planoauditoria.update(planoauditoria_params)
      #Atualiza as auditorias filhas desse plano de auditoria
      @planoauditoria.auditorias.where(status: "Em andamento").update_all status: 'Finalizado' #unless @planoauditoria.encerrado != 1
      redirect_to planos_de_auditorias_path, notice: 'Plano de auditoria atualizado com sucesso.'
    else
      render :edit
    end
  end


  def destroy
    @planoauditoria.destroy
    redirect_to planos_de_auditorias_path, notice: 'Plano de auditoria deletado com sucesso''.'
  end

  private
    def set_planoauditoria
      @planoauditoria = Planoauditoria.find(params[:id])
    end

    def planoauditoria_params
      params.require(:planoauditoria).permit(:nome, :encerrado, :prazo, :ano, {funcionario_ids: []}, :data_inicio, :data_fim)
    end
end

app/views/planosauditorias/_form.html.erb
<%= form_for(@planoauditoria) do |f| %>
  <% if @planoauditoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planoauditoria.errors.count, "error") %> prohibited this planoauditoria from being saved:</h2>

      <ul>
      <% @planoauditoria.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :encerrado %><br>
    <%= f.check_box :encerrado %>
  </div>
  <div class="field">
    <%= f.label :prazo %><br>
    <%= f.number_field :prazo %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.text_field :ano %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planosauditorias/ajax_planos.html.erb
   <%
           if @planos.present?
        %>


            <select name="plano_select" id="plano_select" class="form-control simpleselect">
              <% @planos.each do |p| %>
                  <option value="<%= p.id %>"><%= p.nome %></option>
              <% end %>
            </select>



        <%else%>
            Nenhum plano de auditoria cadastrado
        <% end %>

app/views/planosauditorias/atualizar.html.erb
<script type="application/javascript">

    $(document).ready(function(){
        $(".page-arrow").removeClass("page-arrow");
        $("#menu-auditoria").addClass("menu-open");
        $("#seta-auditoria").removeClass("fa-caret-left");
        $("#seta-auditoria").addClass("fa-caret-down");
        $("#menu-plano-aud").addClass("page-arrow");

        <% if notice.present? %>
            $.e_notify.growl({
                title: 'Sucesso!',
                text: '<%=notice%>',
                position: 'right-bottom',
                delay: 0,
                time: 5000,
                speed: 500,
                effect: 'slidein',
                sticky: false,
                closable: false,
                maxOpen:3,
                className:'',
                onShow: function(){},
                onHide: function(){}
            });
            e.preventDefault();
        <% end %>
    });


</script>





<div id="container" class="clearfix">


  <%=render 'shared/lateral'%>


  <div id="main" class="clearfix">

    <header id="header-main">
      <div class="header-main-top">
        <div class="pull-left">
          <a href="#" id="logo-small"><h4>AMCEL - DMAST</h4><h5>/webapp</h5></a>
        </div>
        <div class="pull-right">

          <a href="#" id="responsive-menu-trigger">
            <i class="fa fa-bars"></i>
          </a>
        </div>
      </div>
      <div class="header-main-bottom">
        <div class="pull-left">
          <ul class="breadcrumb">
            <li><a href="<%=root_path%>">Início</a></li>
            <li><a href="<%=areas_de_atuacao_path%>">Planos de auditorias</a></li>
            <li class="active">Atualização</li>
          </ul>
        </div>
        <%=render 'shared/versao'%>
      </div>
    </header>

    <div id="content" class="clearfix">


      <header id="header-sec">
        <div class="inner-padding">
          <div class="pull-left">
            <h2>Atualização</h2>
          </div>
          <div class="pull-right">



          </div>
        </div><!-- End .inner-padding -->
      </header><!-- End #header-sec -->

      <%= form_for @planoauditoria do |f| %>

          <div class="window">
            <div class="actionbar">
              <div class="pull-left">
                <a href="#" class="btn small-toggle-btn" data-toggle-sidebar="left"></a>
                <a href="#" class="btn" onclick="window.history.go(-1); return false;">
                  <i class="fa fa-arrow-left "></i>&nbsp;Voltar
                </a>

                <button class="btn" type="submit"> <i class="fa fa-check"></i>&nbsp;  Salvar</button>
              </div>



            </div>

            <div class="inner-padding">


              <div class="row">
                <div class="col-sm-12">

                  <fieldset>
                    <legend>Plano de auditoria</legend>
                    <div class="row">
                      <div class="col-sm-2">
                        <label>Nome do plano <span class="asterisk">*</span></label>
                      </div>
                      <div class="col-sm-6">
                        <%= f.text_field :nome, required: true, class: "form-control" %>
                      </div>
                      <div class="col-sm-1 ">
                        <label>Prazo <span class="asterisk">*</span></label>
                      </div>
                      <div class="col-sm-1 col-md-2">
                        <%= f.text_field :prazo, required: true, class: "form-control" %>
                      </div>


                    </div>
                    <div class="spacer-20"></div>
                    <div class="row">
                      <div class="col-sm-2">
                        <label>Destinatários <span class="asterisk">*</span></label>
                      </div>
                      <div class="col-sm-9">
                        <select class="select2" multiple name="planoauditoria[funcionario_ids][]"  id="planoauditoria[funcionario_ids][]" placeholder="Destinatários..">
                          <% @funcionarios.all.each do |f| %>
                            <% pertence = false %>
                            <% @planoauditoria.funcionarios.each do |funcionario| %>
                              <% pertence = true if funcionario.id == f.id %>
                            <% end %>
                            <% if pertence %>
                              <option selected value="<%=f.id%>"><%=f.nome%></option>
                            <% else %>
                              <option value="<%=f.id%>"><%=f.nome%></option>
                            <% end %>
                          <% end %>
                        </select>
                      </div>
                    </div>
                    <div class="spacer-20"></div>
                    <div class="row">
                      <div class="col-sm-2">
                        <label>Status <span class="asterisk">*</span></label>
                      </div>
                      <div class="col-sm-9">

                          <%= f.select :encerrado, [['Em andamento', false], ['Finalizado', true]], {}, { :class => "select2" } %>

                      </div>
                    </div>
                    <div class="spacer-20"></div>
                    <div class="row">
                      <div class="col-sm-2">
                        <label>Ano do plano <span class="asterisk">*</span></label>
                      </div>
                      <div class="col-sm-9">

                        <%= f.text_field :ano, required: true, class: 'form-control', placeholder: 'Digite o ano do plano...', maxlength: '4'  %>

                      </div>
                    </div>

                  </fieldset>

                </div>
              </div>




            </div>
          </div>

      <% end %>

      <%= render 'shared/rodape'%>
    </div><!-- End #content -->
  </div><!-- End #main -->
</div><!-- End #container -->

app/views/planosauditorias/destinatarios.html.erb
<script type="application/javascript">

    $(document).ready(function(){
        $(".page-arrow").removeClass("page-arrow");
        $("#menu-auditoria").addClass("menu-open");
        $("#seta-auditoria").removeClass("fa-caret-left");
        $("#seta-auditoria").addClass("fa-caret-down");
        $("#menu-plano-aud").addClass("page-arrow");

        <% if notice.present? %>
        $.e_notify.growl({
            title: 'Sucesso!',
            text: '<%=notice%>',
            position: 'right-bottom',
            delay: 0,
            time: 5000,
            speed: 500,
            effect: 'slidein',
            sticky: false,
            closable: false,
            maxOpen:3,
            className:'',
            onShow: function(){},
            onHide: function(){}
        });
        e.preventDefault();
        <% end %>
    });


</script>


<!--Modal -->
<div class="modal fade" id="modal-update" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><center>DMAST - AUD</center></h4>
      </div>
      <div class="modal-body">
        <div class="row" style="margin-bottom:-20px">
          <div class="col-xs-12">
            <%= form_for @auditoria do |f| %>



                <div class="row">

                  <div class="col-sm-12">
                    <select class="select2" multiple name="planoauditoria[usuario_ids][]"  id="planoauditoria[usuario_ids][]" placeholder="Destinatários..">
                      <%@usuarios.each do |u| %>
                          <option value="<%=u.id%>"><%=u.nome%></option>
                      <%end%>
                    </select>



                  </div>
                </div>







                <br><br>
                </div>

                </div>
                <div class="modal-footer">
                  <button class="btn btn-danger" data-dismiss="modal"> Cancelar</button>
                  <%= f.submit "Cadastrar", class: "btn btn-success pull-right" do %>
                      <i class="fa fa-search fa-inverse">Salvar</i>
                  <% end %>
            <% end %>
            </div>
            </div>
  </div>
</div></div>




<div id="container" class="clearfix">


  <%=render 'shared/lateral'%>


  <div id="main" class="clearfix">

    <header id="header-main">
      <div class="header-main-top">
        <div class="pull-left">
          <a href="#" id="logo-small"><h4>AMCEL - DMAST</h4><h5>/webapp</h5></a>
        </div>
        <div class="pull-right">

          <a href="#" id="responsive-menu-trigger">
            <i class="fa fa-bars"></i>
          </a>
        </div>
      </div>
      <div class="header-main-bottom">
        <div class="pull-left">
          <ul class="breadcrumb">
            <li><a href="<%=root_path%>">Início</a></li>
            <li class=""><a href="<%=planos_de_auditorias_path%>">Planos de Auditorias</a></li>
            <li class="active">Destinatários</li>
          </ul>
        </div>
        <%=render 'shared/versao'%>
      </div>
    </header>

    <div id="content" class="clearfix">


      <header id="header-sec">
        <div class="inner-padding">
          <div class="pull-left">
            <h2><b>Destinatários do plano</b> - <%=@auditoria.nome%></h2>
          </div>
          <div class="pull-right">



          </div>
        </div><!-- End .inner-padding -->
      </header><!-- End #header-sec -->



      <div class="window">
        <div class="actionbar">
          <div class="pull-left">
            <a href="#" class="btn small-toggle-btn" data-toggle-sidebar="left"></a>

            <a href="<%=planos_de_auditorias_path%>" class="btn" id="" onclick="history.go(-1);">
              <i class="fa fa-arrow-circle-o-left"></i>&nbsp;  Voltar
            </a>
            <a href="#" class="btn" id="modal-update-trigger">
              <i class="fa fa-plus-circle"></i>&nbsp;  Incluir
            </a>

          </div>

          <div class="pull-right">

          </div>



        </div>

        <div class="inner-padding">


          <% if @auditoria.usuarios.present? %>
              <table class="table col-md-12" id="tablesorting-1">
                <thead class="">
                <tr>
                  <th class="col-md-10">Usuário</th>

                  <th class="col-md-2">Opções</th>
                </tr>
                </thead>
                <tbody>
                <% @auditoria.usuarios.each do |p| %>
                    <tr>
                      <td><%= p.nome %></td>



                      <td>
                        <center>
                          <%= link_to p, method: :delete, data: { confirm: 'Tem Certeza?' }, class: "btn-less tooltip-top", id: "deletar", title: "Remover" do %>
                              <i class="fa fa-trash-o"></i>
                          <% end %>
                        </center>
                      </td>
                    </tr>
                <% end %>
                </tbody>
                <tfoot>
                <tr>
                  <td colspan="2" class="pager form-horizontal">
                    <button class="btn first"><i class="fa fa-step-backward"></i></button>
                    <button class="btn prev"><i class="fa fa-arrow-left"></i></button>
                    <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
                    <button class="btn next"><i class="fa fa-arrow-right"></i></button>
                    <button class="btn last"><i class="fa fa-step-forward"></i></button>
                    <select class="pagesize input-xs" title="Select page size">
                      <option selected="selected" value="10">10</option>
                      <option value="20">20</option>
                      <option value="30">30</option>
                      <option value="40">40</option>
                    </select>
                    <select class="pagenum input-xs" title="Select page number"></select>
                  </td>
                </tr>
                </tfoot>
              </table>

          <% else %>
              <div class="alert alert-block alert-inline-top alert-dismissable">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4>nenhum usuário nesse plano</h4>

              </div>
          <% end %>






        </div>
      </div>


      <%= render 'shared/rodape'%>
    </div><!-- End #content -->
  </div><!-- End #main -->
</div><!-- End #container -->

app/views/planosauditorias/edit.html.erb
<h1>Editing planoauditoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @planoauditoria %> |
<%= link_to 'Back', planosauditorias_path %>

app/views/planosauditorias/new.html.erb
<h1>New planoauditoria</h1>

<%= render 'form' %>

<%= link_to 'Back', planosauditorias_path %>

app/views/planosauditorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @planoauditoria.nome %>
</p>

<p>
  <strong>Encerrado:</strong>
  <%= @planoauditoria.encerrado %>
</p>

<p>
  <strong>Prazo:</strong>
  <%= @planoauditoria.prazo %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @planoauditoria.ano %>
</p>

<%= link_to 'Edit', edit_planoauditoria_path(@planoauditoria) %> |
<%= link_to 'Back', planosauditorias_path %>