config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'admin'
  end



  mount Sidekiq::Web, at: '/sidekiq'

  resources :filiais

  get 'demais_racs/index'

  resources :helpers

  resources :demais_racs do
    member do
      get :atualizar
    end
  end

  resources :grp_consensadores
  resources :grp_homologadores

  resources :followups

  resources :documento_localizacoes

  get 'anexo_documentos/new'

  get 'anexo_documentos/create'

  get 'anexo_documentos/anexo_params'

  resources :anexo_docs

  resources :consensadores

  resources :homologadores

  resources :consensamentos

  resources :documentos do
    member do

      get :novo



    end
  end

  get 'anexo_reunioes/new'

  get 'anexo_reunioes/create'

  resources :topicos

  resources :locais

  resources :raps do
    member do
      get :atualizar
      get :alterar_data_acao
    end
  end

  resources :racs do
    member do
      get :atualizar
      get :alterar_data_acao
    end
  end

  resources :rais do
    member do
      get :atualizar
    end
  end

  resources :reunioes do
    member do
      get :atualizar
    end
  end

  resources :planosauditorias do
    member do
      get :atualizar
    end
  end

  resources :funcionarios

  get 'grupos/index'

  resources :tipo_racs do
    member do
      get :atualizar
    end
  end



  resources :tipo_docs do
    member do
      get :atualizar
    end
  end

  resources :tipo_ncs do
    member do
      get :atualizar
    end
  end

  resources :areas do
    member do
      get :atualizar
    end
  end

  resources :pastas do
    member do
      get :atualizar
    end
  end  

  resources :numeros do
    member do
      get :atualizar
    end
  end  

  resources :localizacoes do
    member do
      get :atualizar
    end
  end  

  resources :tipo_atas do
    member do
      get :atualizar
    end
  end

  resources :funcionarios do
    member do
      get :atualizar
    end
  end

  resources :auditorias do
    member do
      get :atualizar
      get :imprimir
      get :visualizar
    end
  end

  resource :anexo_reunioes do
    member do
      get :salvar
    end
  end

  get 'notificacoes/visto'

  get 'notificacoes/listar'

  get 'sessions/create'
  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'sair', to: 'sessions#destroy', as: 'signout'
  get 'sessions/nao_autorizado'

  get 'home/index'
  get 'notificacoes/pesquisar'

  match 'ajax_planos', controller: 'planosauditorias', action: 'ajax_planos', via: 'get'
  match 'ajax_ajuda', controller: 'helpers', action: 'ajax_ajuda', via: 'get'

  match 'editar-grupo-consenso-:id', controller: 'grp_consensadores', action: 'edit', via: 'get'
  match 'editar-grupo-consenso', controller: 'grp_consensadores', action: 'update', via: 'post'
  match 'editar-grupo-consenso', controller: 'grp_consensadores', action: 'update', via: 'patch'

  match 'editar-grupo-homologacao-:id', controller: 'grp_homologadores', action: 'edit', via: 'get'
  match 'editar-grupo-homologacao', controller: 'grp_homologadores', action: 'update', via: 'post'
  match 'editar-grupo-homologacao', controller: 'grp_homologadores', action: 'update', via: 'patch'

  match 'visualizar-documentos-:filtro', controller: 'documentos', action: 'index', via: 'get'
  match 'imprimir-rac-:id', controller: 'racs', action: 'print', via: 'get'
  match 'imprimir-rai-:id', controller: 'rais', action: 'print', via: 'get'
  match 'imprimir-rap-:id', controller: 'raps', action: 'print', via: 'get'
  match 'imprimir-demais-rac-:id', controller: 'demais_racs', action: 'print', via: 'get'
  match 'visualizar-documento-:id', controller: 'documentos', action: 'visualizar', via: 'get'
  match 'documentos-excluidos', controller: 'documentos', action: 'lixeira', via: 'get'
  match 'consenso-documento-:id', controller: 'documentos', action: 'visualizar_via_email', via: 'get'

  match 'racs', controller: 'racs', action: 'index', via: 'get'


  match 'racs,visualizar,:filtro', controller: 'racs', action: 'lista', via: 'get'

  match 'enviar-doc-lixeira', controller: 'documentos', action: 'enviar_lixeira', via: 'post'
  match 'restaurar-doc-lixeira', controller: 'documentos', action: 'restaurar_lixeira', via: 'post'

  match 'demais-racs', controller: 'demais_racs', action: 'index', via: 'get'
  match 'inserir-demais-racs', controller: 'demais_racs', action: 'inserir', via: 'get'
  match 'raps', controller: 'raps', action: 'lista', via: 'get'

  match 'backup', controller: 'backup', action: 'do', via: 'get'

  match 'lista-auditorias-:id', controller: 'auditorias', action: 'lista', via: 'get'
  match 'visualizar-auditoria-:id', controller: 'auditorias', action: 'show', via: 'get'
  match 'download-anexo-:id', controller: 'reunioes', action: 'download_anexo', via: 'get'
  match 'doc-download-anexo-:id', controller: 'documentos', action: 'download_anexo', via: 'get'
  match 'visualizar-notificacao-:id', controller: 'notificacoes', action: 'visualizar', via: 'get'
  match 'anexar-arquivo-na-reuniao-:id', controller: 'reunioes', action: 'anexar', via: 'get'
  match 'adicionar-anexo-doc-:doc_id', controller: 'documentos', action: 'anexar', via: 'get'


  match 'adiamentos,rac,:id', controller: 'racs', action: 'ver_adiamentos', via: 'get'
  match 'gerenciar-ajuda', controller: 'helpers', action: 'index', via: 'get'

  match 'lista-de-racs', controller: 'racs', action: 'index', via: 'get'

  get 'ajax-salva-topico/:reuniao_id/:descricao', controller: 'reunioes', action: 'salva_topico', via: 'get'
  get 'encerrar-reuniao-:id', controller: 'reunioes', action: 'encerrar_reuniao', via: 'get'

  match 'relatorios-de-auditorias-internas', controller: 'rais', action: 'index', via: 'get'

  match 'auditorias,plano,:id', controller: 'auditorias', action: 'index', via: 'get'

  match 'marcar,como,finalizada,:id', controller: 'reunioes', action: 'marcar_finalizada', via: 'get'
  match 'excluir,topico,:id', controller:'reunioes', action: 'excluir_topico', via: 'get'

  match 'areas-de-atuacao', controller: 'areas', action: 'index', via: 'get'
  match 'ver-notificacoes', controller: 'notificacoes', action: 'listar', via: 'get'
  match 'tipos-de-atas', controller: 'tipo_atas', action: 'index', via: 'get'
  match 'tipos-de-ncs', controller: 'tipo_ncs', action: 'index', via: 'get'
  match 'tipos-de-docs', controller: 'tipo_docs', action: 'index', via: 'get'
  match 'tipos-de-racs', controller: 'tipo_racs', action: 'index', via: 'get'

  match 'planos-de-auditorias', controller: 'planosauditorias', action: 'index', via: 'get'

  match 'reunioes', controller: 'reunioes', action: 'index', via: 'get'

  match 'nova-reuniao', controller: 'reunioes', action: 'incluir', via: 'get'

  match 'rqa', controller: 'rqas', action: 'incluir', via: 'get'

  match 'lista-de-funcionarios', controller: 'funcionarios', action: 'index', via: 'get'
  match 'lista-de-funcionarios-2', controller: 'funcionarios', action: 'lista_funcionarios', via: 'get'

  match 'grupos-de-usuarios', controller: 'grupos', action: 'index', via: 'get'

  match 'cadastrar-nova-rai', controller: 'rais', action: 'new', via: 'get'
  match 'cadastrar-nova-rac', controller: 'racs', action: 'new', via: 'get'
  match 'cadastrar-nova-rap', controller: 'raps', action: 'new', via: 'get'
  match 'elaborar-documento', controller: 'documentos', action: 'new', via: 'get'


  match 'lista-de-raps', controller: 'raps', action: 'index', via: 'get'
  match 'ajax-lista-auditorias-:id', controller: 'auditorias', action: 'lista', via: 'get'
  match 'ajax-novo-topico-:reuniao_id', controller: 'topicos', action: 'add', via: 'get'

  match 'destinatarios-do-plano-auditoria,:id', controller: 'planosauditorias', action: 'destinatarios', via: 'get'
  match 'notificar-destinatarios-do-plano,:id', controller: 'planosauditorias', action: 'notificar_destinatarios', via: 'get'
  match 'apagar,auditoria,:id', controller: 'auditorias', action: 'delete', via: 'get'

  match 'grupo-consensadores', controller: 'grp_consensadores', action: 'index', via: 'get'
  match 'grupo-homologadores', controller: 'grp_homologadores', action: 'index', via: 'get'

  match 'iniciar-workflow-:id', controller: 'documentos', action: 'consensar', via: 'get'
  match 'enviar-para-consenso-:id', controller: 'documentos', action: 'enviar_consenso', via: 'get'

  post 'recebe-resposta-consenso', controller: 'documentos', action: 'recebe_resposta_consenso', via: 'post'
  get 'rqas', controller: 'rqas', action: 'index', via: 'get'
  post 'salva-rqa', controller: 'rqas', action: 'salvar', via: 'post'

  get 'confirmar-consenso-:id', controller: 'documentos', action: 'recebe_resposta_consenso', via: 'get'

  get 'homologar-documento-:id', controller: 'documentos', action: 'homologar', via: 'get'

  post 'recebe-resposta-homologacao', controller: 'documentos', action: 'recebe_resposta_homologacao', via: 'post'

  get 'confirmar-homologacao-:id', controller: 'documentos', action: 'recebe_resposta_homologacao', via: 'get'

  get 'add-atv-auditoria-:id', controller: 'auditorias', action: 'add_atividade', via: 'get'
  get 'del-atv-:id', controller: 'auditorias', action: 'del_atividade', via: 'get'

  post 'salva-atividade', controller: 'auditorias', action: 'salva_atividade', via: 'post'

  get 'follow-up-auditoria-:id', controller: 'followups', action: 'new', via: 'post'

  post '/tinymce_assets' => 'uploadimg#create'

  get 'atualizar-documento-:id', controller: 'documentos', action: 'edit', via: 'post'


  get 'adicionar-localizacao-doc-:id', controller: 'documento_localizacoes', action: 'new', via: 'get'

  get 'add-destinatarios', controller: 'followups', action: 'add_destinatario', via: 'post'

  get 'disparar-followup-:id', controller: 'auditorias', action: 'disparar_followup', via: 'post'

app/models/funcionario.rb
# == Schema Information
#
# Table name: funcionarios
#
#  id         :integer          not null, primary key
#  chapa      :string(10)       not null
#  nome       :string(80)       not null
#  ativo      :boolean          default(TRUE), not null
#  email      :string(200)
#  filial_id  :integer          not null
#  area_id    :integer
#  grupo_id   :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Funcionario < ActiveRecord::Base
  belongs_to :filial
  belongs_to :area
  belongs_to :grupo
  has_and_belongs_to_many :auditorias, join_table: :auditorias_funcionarios
  has_and_belongs_to_many :reunioes, join_table: :reunioes_usuarios
  has_and_belongs_to_many :planosauditorias, join_table: :planos_funcionarios
  has_and_belongs_to_many :grp_consensador, join_table: :grpconsensador_funcionarios, class_name: 'GrpConsensador'
  has_and_belongs_to_many :grp_homologador, join_table: :grphomologadores_funcionarios, class_name: 'GrpHomologador'


  scope :ativos, -> {
    where(ativo: true)
    .order("nome asc")
  }

  scope :ativos_com_email, -> {
    where(ativo: true).
    where.not(email: nil).
    order("nome asc")
  }

end

app/controllers/api/v1/funcionarios.rb
module API
  module V1
    class Funcionarios < Grape::API
      version 'v1'
      format :json

      resources :funcionarios do
        desc "Retorna todos os funcionários"
        get do
          Funcionario.all
        end
      end

    end
  end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_usuario, only: [:destroy, :atualizar, :update]
  before_filter :require_user
  respond_to :json, :html

  def index
    if params[:search] 
      @funcionarios = Funcionario.where("nome like '%#{params[:search]}%' or email like '%#{params[:search]}%'").includes(:grupo).paginate(:page => params[:page], :per_page => 10).order(:nome)
    else
      @funcionarios = Funcionario.includes(:grupo).paginate(:page => params[:page], :per_page => 10).order(:nome)
    end

    if params[:filter]
      if params[:filter] == 'ativos'
        @funcionarios = @funcionarios.where(ativo: true)
      else
        @funcionarios = @funcionarios.where(ativo: false)
      end
    end
    
    @funcionario = Funcionario.new
    @grupos = Grupo.order :descricao
    respond_with @funcionarios
  end

  def atualizar
    @grupos = Grupo.all.order :descricao
  end

  def update
    if @funcionario.update(funcionario_params)
      redirect_to lista_de_funcionarios_path, notice: 'Funcionário atualizado!'
    else
      render :edit
    end
  end

  def create
    @funcionario = Funcionario.new(funcionario_params)

    if @funcionario.save
      redirect_to lista_de_funcionarios_path, notice: 'Cadastro realizado!'
    else
      render :new
    end
  end

  def destroy
    @funcionario.ativo = !@funcionario.ativo
    @funcionario.save!
    redirect_to lista_de_funcionarios_path, notice: "Funcionário atualizado!" 
  end

  private
    def funcionario_params
      params.require(:funcionario).permit(:nome, :email, :grupo_id, :chapa, :nome, :filial_id, :area_id)
    end

    def set_usuario
      @funcionario = Funcionario.find(params[:id])
    end

end

app/views/funcionarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :grupo_id %><br>
    <%= f.text_field :grupo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funcionarios/atualizar.html.erb
<script type="application/javascript">

    $(document).ready(function(){
        $(".page-arrow").removeClass("page-arrow");
        $("#menu-usuarios").addClass("page-arrow");
    });


</script>





<div id="container" class="clearfix">


  <%=render 'shared/lateral'%>


  <div id="main" class="clearfix">

    <header id="header-main">
      <div class="header-main-top">
        <div class="pull-left">
          <a href="#" id="logo-small"><h4>AMCEL - DMAST</h4><h5>/webapp</h5></a>
        </div>
        <div class="pull-right">

          <a href="#" id="responsive-menu-trigger">
            <i class="fa fa-bars"></i>
          </a>
        </div>
      </div>
      <div class="header-main-bottom">
        <div class="pull-left">
          <ul class="breadcrumb">
            <li><a href="<%=root_path%>">Início</a></li>
            <li><a href="<%=areas_de_atuacao_path%>">Usuário</a></li>
            <li class="active">Editar</li>
          </ul>
        </div>
        <%=render 'shared/versao'%>
      </div>
    </header>

    <div id="content" class="clearfix">


      <header id="header-sec">
        <div class="inner-padding">
          <div class="pull-left">
            <h2>Alterar dados</h2>
          </div>
          <div class="pull-right">



          </div>
        </div><!-- End .inner-padding -->
      </header><!-- End #header-sec -->

      <%= form_for(@funcionario) do |f| %>

          <div class="window">
            <div class="actionbar">
              <div class="pull-left">
                <a href="#" class="btn small-toggle-btn" data-toggle-sidebar="left"></a>
                <a href="#" class="btn" onclick="window.history.go(-1); return false;">
                  <i class="fa fa-arrow-left "></i>&nbsp;Voltar
                </a>

                <button type="submit" class="btn"><i class="fa fa-check-circle "></i>&nbsp;Salvar</button>

              </div>



            </div>

            <div class="inner-padding">


              <div class="row">
                <div class="col-sm-12">

                  <fieldset>
                    <legend>Usuário</legend>
                    <div class="row">
                      <div class="col-sm-2">
                        <label>Nome: <span class="asterisk">*</span></label>
                      </div>
                      <div class="col-sm-9">
                        <%= f.text_field :nome, required: true, class: "form-control" %>
                      </div>
                    </div>

                    <div class="spacer-20"></div>

                    <div class="row">
                      <div class="col-sm-2">
                        <label>E-Mail: <span class="asterisk">*</span></label>
                      </div>
                      <div class="col-sm-9">
                        <%= f.text_field :email, required: true, class: "form-control" %>
                      </div>
                    </div>

                    <div class="spacer-20"></div>

                    <div class="row">
                      <div class="col-sm-2">
                        <label>Grupo: <span class="asterisk">*</span></label>
                      </div>
                      <div class="col-sm-9">
                        <%= f.collection_select :grupo_id, @grupos, :id, :descricao, {}, { :class => "select2" }  %>
                      </div>
                    </div>
                  </fieldset>

                </div>
              </div>






            </div>
          </div>

      <% end %>

      <%= render 'shared/rodape'%>
    </div><!-- End #content -->
  </div><!-- End #main -->
</div><!-- End #container -->

app/views/funcionarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/funcionarios/index.html.erb
<script type="application/javascript">

    $(document).ready(function(){
        $(".page-arrow").removeClass("page-arrow");
        $("#menu-funcionarios").addClass("page-arrow");

        <% if notice.present? %>
        $.e_notify.growl({
            title: 'Sucesso!',
            text: '<%=notice%>',
            position: 'right-bottom',
            delay: 0,
            time: 5000,
            speed: 500,
            effect: 'slidein',
            sticky: false,
            closable: false,
            maxOpen:3,
            className:'',
            onShow: function(){},
            onHide: function(){}
        });
        e.preventDefault();
        <% end %>
    });


</script>

<!--Modal -->
<div class="modal fade" id="modal-update" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><center>DMAST - Cadastro de funcionário</center></h4>
      </div>
      <div class="modal-body">
        <div class="row" style="margin-bottom:-20px">
          <div class="col-xs-12">
            <%= form_for @funcionario do |f| %>

                <div class="row">
                  <div class="col-sm-6">
                    <label>Chapa:</label>
                  </div>
                  <div class="col-sm-12">
                    <%= f.text_field :chapa, required: true, class: "form-control", placeholder: "", autofocus: true %>
                        </div>
                        </div>

                        <div class="spacer-20"></div>

                <div class="row">
                  <div class="col-sm-6">
                    <label>Nome Completo:</label>
                  </div>
                  <div class="col-sm-12">
                    <%= f.text_field :nome, required: true, class: "form-control", placeholder: "", autofocus: true %>
                        </div>
                        </div>

                        <div class="spacer-20"></div>

                <div class="row">
                  <div class="col-sm-6">
                    <label>E-Mail:</label>
                  </div>
                  <div class="col-sm-12">
                    <%= f.text_field :email, required: true, class: "form-control", placeholder: "", autofocus: true %>
                  </div>
                </div>

                <div class="spacer-20"></div>
                        <div class="row">
                          <div class="col-sm-6">
                            <label>Filial:</label>
                          </div>
                          <div class="col-sm-12">
                            <%= f.collection_select :filial_id, Filial.all, :id, :nome, {}, { :class => "select2" }  %>
                                </div>
                                </div>


                        <div class="spacer-20"></div>
                        <div class="row">
                          <div class="col-sm-6">
                            <label>Área:</label>
                          </div>
                          <div class="col-sm-12">
                            <%= f.collection_select :area_id, Area.all, :id, :descricao, {}, { :class => "select2" }  %>
                          </div>
                        </div>

                        <div class="spacer-20"></div>


                <div class="row">
                  <div class="col-sm-6">
                    <label>Grupo:</label>
                  </div>
                  <div class="col-sm-12">
                    <%= f.collection_select :grupo_id, @grupos, :id, :descricao, {}, { :class => "select2" }  %>
                  </div>
                </div>




                <br><br>
                </div>
                </div>
                </div>
                <div class="modal-footer">
                  <button class="btn btn-danger" data-dismiss="modal"> Cancelar</button>
                  <%= f.submit "Cadastrar", class: "btn btn-success pull-right" do %>
                      <i class="fa fa-search fa-inverse">Cadastrar</i>
                  <% end %>
            <% end %>
            </div>
            </div>
  </div>
</div>



<div id="container" class="clearfix">


  <%=render 'shared/lateral'%>


  <div id="main" class="clearfix">

    <header id="header-main">
      <div class="header-main-top">
        <div class="pull-left">
          <a href="#" id="logo-small"><h4>AMCEL - DMAST</h4><h5>/webapp</h5></a>
        </div>
        <div class="pull-right">

          <a href="#" id="responsive-menu-trigger">
            <i class="fa fa-bars"></i>
          </a>
        </div>
      </div>
      <div class="header-main-bottom">
        <div class="pull-left">
          <ul class="breadcrumb">
            <li><a href="<%=root_path%>">Início</a></li>
            <li class="active">Funcionários</li>
          </ul>
        </div>
        <%=render 'shared/versao'%>
      </div>
    </header>

    <div id="content" class="clearfix">
      <header id="header-sec">
        <div class="inner-padding">
          <div class="pull-left">
            <h2>Funcionários</h2>
          </div>
          <div class="pull-right">
                            <form class="input-group width-400">
                                <input required type="text" name="search" class="form-control" placeholder="Nome ou E-Mail" id="typeahead-sidebar-search"/>
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                                </div>
                            </form> 
                            
                        </div> 
        </div>


      </header>
      <div class="window">
        <div class="actionbar">
          <div class="pull-left">
            <a href="#" class="btn small-toggle-btn" data-toggle-sidebar="left"></a>
            <a href="#" class="btn" id="modal-update-trigger">
              <i class="fa fa-plus-circle"></i>&nbsp;  Cadastrar funcionário
            </a>
          </div>
          <div class="pull-right">
          <div class="dropdown">
                                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-fw">&#xf0b0</i>
Filtro
                                    <i class="fa fa-caret-down"></i>
                                </a>
                                <ul role="menu" class="dropdown-menu pull-right ext-dropdown-icons-right">
                                    <li>
                                        <a href="/funcionarios">Todos <img src="images/icons/flags/shiny/16/United-Kingdom.png" alt=""/></a>
                                    </li>
                                    <li>
                                        <a href="?filter=ativos">Ativos</a>
                                    </li>
                                    <li>
                                        <a href="?filter=inativos">Inativos</a>
                                    </li>
                                </ul>
                            </div> 
          </div>
        </div>

        <div class="inner-padding">


          <% if @funcionarios.present? %>
            <% if @funcionarios.where("email is null or email = ''").count > 1 %>
                        <div class="alert alert-warning">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <i class="fa fa-warning"></i>Alguns funcionários não possuem e-mail cadastrado, eles não poderam ser utilizados em processo de workflow.
                        </div> 
            <% end %>
                        
              <table class="table table-bordered col-md-12" id="">
                <thead class="">
                <tr>
                  <th class="filter-select filter-exact col-md-1" data-placeholder="Todos...">Status</th>
                  <th class="col-md-4">Nome</th>
                  <th class="col-md-4">E-Mail</th>
                  <th class="filter-select filter-exact col-md-2" data-placeholder="Todos...">Grupo</th>
                  <th class="col-md-2">Opções</th>
                </tr>
                </thead>
                <tbody>
                <% @funcionarios.each do |u| %>
                    <tr>
                      <% if u.ativo %>
                        <td>Ativo</td>
                      <% else %>
                        <td>Inativo</td>
                      <% end %>
                      <td><%= u.nome %></td>
                      <td><%= u.email %></td>
                      <td><center><%= u.grupo.descricao%></center></td>
                      <td>
                        <center>
                          <%= link_to atualizar_funcionario_path(u), class: "btn-less", id: "deletar" do %>
                              <i class="fa fa-pencil"></i>
                          <% end %>
                          <a href="#" class="btn-less"></a>

                          <%= link_to u, method: :delete, class: "btn-less", id: "deletar" do %>
                              <% if u.ativo %>
                                <i class="fa fa-lock"></i>
                              <% else %>
                                  <i class="fa fa-unlock"></i>
                              <% end %>
                          <% end %>
                        </center>
                      </td>
                    </tr>
                <% end %>
                </tbody>
                <tfoot>
                <tr>
                  
                </tr>
                </tfoot>

              </table>
              <div class="spacer-20"></div>
              <div class="pull-left">
                                    <%= will_paginate @funcionarios %>
                                </div>
                            

          <% else %>
              <div class="alert alert-block alert-inline-top alert-dismissable">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4>Nenhum funcionário encontrado</h4>
              </div>
          <% end %>

        </div>
      </div>


      <%= render 'shared/rodape'%>
    </div><!-- End #content -->
  </div><!-- End #main -->
</div><!-- End #container -->

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @usuario.grupo %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>