config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'admin'
  end



  mount Sidekiq::Web, at: '/sidekiq'

  resources :filiais

  get 'demais_racs/index'

  resources :helpers

  resources :demais_racs do
    member do
      get :atualizar
    end
  end

  resources :grp_consensadores
  resources :grp_homologadores

  resources :followups

  resources :documento_localizacoes

  get 'anexo_documentos/new'

  get 'anexo_documentos/create'

  get 'anexo_documentos/anexo_params'

  resources :anexo_docs

  resources :consensadores

  resources :homologadores

  resources :consensamentos

  resources :documentos do
    member do

      get :novo



    end
  end

  get 'anexo_reunioes/new'

  get 'anexo_reunioes/create'

  resources :topicos

  resources :locais

  resources :raps do
    member do
      get :atualizar
      get :alterar_data_acao
    end
  end

  resources :racs do
    member do
      get :atualizar
      get :alterar_data_acao
    end
  end

  resources :rais do
    member do
      get :atualizar
    end
  end

  resources :reunioes do
    member do
      get :atualizar
    end
  end

  resources :planosauditorias do
    member do
      get :atualizar
    end
  end

  resources :funcionarios

  get 'grupos/index'

  resources :tipo_racs do
    member do
      get :atualizar
    end
  end



  resources :tipo_docs do
    member do
      get :atualizar
    end
  end

  resources :tipo_ncs do
    member do
      get :atualizar
    end
  end

  resources :areas do
    member do
      get :atualizar
    end
  end

  resources :pastas do
    member do
      get :atualizar
    end
  end  

  resources :numeros do
    member do
      get :atualizar
    end
  end  

  resources :localizacoes do
    member do
      get :atualizar
    end
  end  

  resources :tipo_atas do
    member do
      get :atualizar
    end
  end

  resources :funcionarios do
    member do
      get :atualizar
    end
  end

  resources :auditorias do
    member do
      get :atualizar
      get :imprimir
      get :visualizar
    end
  end

  resource :anexo_reunioes do
    member do
      get :salvar
    end
  end

  get 'notificacoes/visto'

  get 'notificacoes/listar'

  get 'sessions/create'
  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'sair', to: 'sessions#destroy', as: 'signout'
  get 'sessions/nao_autorizado'

  get 'home/index'
  get 'notificacoes/pesquisar'

  match 'ajax_planos', controller: 'planosauditorias', action: 'ajax_planos', via: 'get'
  match 'ajax_ajuda', controller: 'helpers', action: 'ajax_ajuda', via: 'get'

  match 'editar-grupo-consenso-:id', controller: 'grp_consensadores', action: 'edit', via: 'get'
  match 'editar-grupo-consenso', controller: 'grp_consensadores', action: 'update', via: 'post'
  match 'editar-grupo-consenso', controller: 'grp_consensadores', action: 'update', via: 'patch'

  match 'editar-grupo-homologacao-:id', controller: 'grp_homologadores', action: 'edit', via: 'get'
  match 'editar-grupo-homologacao', controller: 'grp_homologadores', action: 'update', via: 'post'
  match 'editar-grupo-homologacao', controller: 'grp_homologadores', action: 'update', via: 'patch'

  match 'visualizar-documentos-:filtro', controller: 'documentos', action: 'index', via: 'get'
  match 'imprimir-rac-:id', controller: 'racs', action: 'print', via: 'get'
  match 'imprimir-rai-:id', controller: 'rais', action: 'print', via: 'get'
  match 'imprimir-rap-:id', controller: 'raps', action: 'print', via: 'get'
  match 'imprimir-demais-rac-:id', controller: 'demais_racs', action: 'print', via: 'get'
  match 'visualizar-documento-:id', controller: 'documentos', action: 'visualizar', via: 'get'
  match 'documentos-excluidos', controller: 'documentos', action: 'lixeira', via: 'get'
  match 'consenso-documento-:id', controller: 'documentos', action: 'visualizar_via_email', via: 'get'

  match 'racs', controller: 'racs', action: 'index', via: 'get'


  match 'racs,visualizar,:filtro', controller: 'racs', action: 'lista', via: 'get'

  match 'enviar-doc-lixeira', controller: 'documentos', action: 'enviar_lixeira', via: 'post'
  match 'restaurar-doc-lixeira', controller: 'documentos', action: 'restaurar_lixeira', via: 'post'

  match 'demais-racs', controller: 'demais_racs', action: 'index', via: 'get'
  match 'inserir-demais-racs', controller: 'demais_racs', action: 'inserir', via: 'get'
  match 'raps', controller: 'raps', action: 'lista', via: 'get'

  match 'backup', controller: 'backup', action: 'do', via: 'get'

  match 'lista-auditorias-:id', controller: 'auditorias', action: 'lista', via: 'get'
  match 'visualizar-auditoria-:id', controller: 'auditorias', action: 'show', via: 'get'
  match 'download-anexo-:id', controller: 'reunioes', action: 'download_anexo', via: 'get'
  match 'doc-download-anexo-:id', controller: 'documentos', action: 'download_anexo', via: 'get'
  match 'visualizar-notificacao-:id', controller: 'notificacoes', action: 'visualizar', via: 'get'
  match 'anexar-arquivo-na-reuniao-:id', controller: 'reunioes', action: 'anexar', via: 'get'
  match 'adicionar-anexo-doc-:doc_id', controller: 'documentos', action: 'anexar', via: 'get'


  match 'adiamentos,rac,:id', controller: 'racs', action: 'ver_adiamentos', via: 'get'
  match 'gerenciar-ajuda', controller: 'helpers', action: 'index', via: 'get'

  match 'lista-de-racs', controller: 'racs', action: 'index', via: 'get'

  get 'ajax-salva-topico/:reuniao_id/:descricao', controller: 'reunioes', action: 'salva_topico', via: 'get'
  get 'encerrar-reuniao-:id', controller: 'reunioes', action: 'encerrar_reuniao', via: 'get'

  match 'relatorios-de-auditorias-internas', controller: 'rais', action: 'index', via: 'get'

  match 'auditorias,plano,:id', controller: 'auditorias', action: 'index', via: 'get'

  match 'marcar,como,finalizada,:id', controller: 'reunioes', action: 'marcar_finalizada', via: 'get'
  match 'excluir,topico,:id', controller:'reunioes', action: 'excluir_topico', via: 'get'

  match 'areas-de-atuacao', controller: 'areas', action: 'index', via: 'get'
  match 'ver-notificacoes', controller: 'notificacoes', action: 'listar', via: 'get'
  match 'tipos-de-atas', controller: 'tipo_atas', action: 'index', via: 'get'
  match 'tipos-de-ncs', controller: 'tipo_ncs', action: 'index', via: 'get'
  match 'tipos-de-docs', controller: 'tipo_docs', action: 'index', via: 'get'
  match 'tipos-de-racs', controller: 'tipo_racs', action: 'index', via: 'get'

  match 'planos-de-auditorias', controller: 'planosauditorias', action: 'index', via: 'get'

  match 'reunioes', controller: 'reunioes', action: 'index', via: 'get'

  match 'nova-reuniao', controller: 'reunioes', action: 'incluir', via: 'get'

  match 'rqa', controller: 'rqas', action: 'incluir', via: 'get'

  match 'lista-de-funcionarios', controller: 'funcionarios', action: 'index', via: 'get'
  match 'lista-de-funcionarios-2', controller: 'funcionarios', action: 'lista_funcionarios', via: 'get'

  match 'grupos-de-usuarios', controller: 'grupos', action: 'index', via: 'get'

  match 'cadastrar-nova-rai', controller: 'rais', action: 'new', via: 'get'
  match 'cadastrar-nova-rac', controller: 'racs', action: 'new', via: 'get'
  match 'cadastrar-nova-rap', controller: 'raps', action: 'new', via: 'get'
  match 'elaborar-documento', controller: 'documentos', action: 'new', via: 'get'


  match 'lista-de-raps', controller: 'raps', action: 'index', via: 'get'
  match 'ajax-lista-auditorias-:id', controller: 'auditorias', action: 'lista', via: 'get'
  match 'ajax-novo-topico-:reuniao_id', controller: 'topicos', action: 'add', via: 'get'

  match 'destinatarios-do-plano-auditoria,:id', controller: 'planosauditorias', action: 'destinatarios', via: 'get'
  match 'notificar-destinatarios-do-plano,:id', controller: 'planosauditorias', action: 'notificar_destinatarios', via: 'get'
  match 'apagar,auditoria,:id', controller: 'auditorias', action: 'delete', via: 'get'

  match 'grupo-consensadores', controller: 'grp_consensadores', action: 'index', via: 'get'
  match 'grupo-homologadores', controller: 'grp_homologadores', action: 'index', via: 'get'

  match 'iniciar-workflow-:id', controller: 'documentos', action: 'consensar', via: 'get'
  match 'enviar-para-consenso-:id', controller: 'documentos', action: 'enviar_consenso', via: 'get'

  post 'recebe-resposta-consenso', controller: 'documentos', action: 'recebe_resposta_consenso', via: 'post'
  get 'rqas', controller: 'rqas', action: 'index', via: 'get'
  post 'salva-rqa', controller: 'rqas', action: 'salvar', via: 'post'

  get 'confirmar-consenso-:id', controller: 'documentos', action: 'recebe_resposta_consenso', via: 'get'

  get 'homologar-documento-:id', controller: 'documentos', action: 'homologar', via: 'get'

  post 'recebe-resposta-homologacao', controller: 'documentos', action: 'recebe_resposta_homologacao', via: 'post'

  get 'confirmar-homologacao-:id', controller: 'documentos', action: 'recebe_resposta_homologacao', via: 'get'

  get 'add-atv-auditoria-:id', controller: 'auditorias', action: 'add_atividade', via: 'get'
  get 'del-atv-:id', controller: 'auditorias', action: 'del_atividade', via: 'get'

  post 'salva-atividade', controller: 'auditorias', action: 'salva_atividade', via: 'post'

  get 'follow-up-auditoria-:id', controller: 'followups', action: 'new', via: 'post'

  post '/tinymce_assets' => 'uploadimg#create'

  get 'atualizar-documento-:id', controller: 'documentos', action: 'edit', via: 'post'


  get 'adicionar-localizacao-doc-:id', controller: 'documento_localizacoes', action: 'new', via: 'get'

  get 'add-destinatarios', controller: 'followups', action: 'add_destinatario', via: 'post'

  get 'disparar-followup-:id', controller: 'auditorias', action: 'disparar_followup', via: 'post'

app/models/topico.rb
# == Schema Information
#
# Table name: topicos
#
#  id         :integer          not null, primary key
#  descricao  :string(255)
#  encerrado  :boolean
#  reuniao_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Topico < ActiveRecord::Base
  belongs_to :reuniao
end

app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  before_action :set_topico, only: [:show, :edit, :update, :destroy]
  before_filter :require_user
  def index
    @topicos = Topico.all
  end

  def show
  end

  def new
    @topico = Topico.new
  end

  def add
    @topico = Topico.new
    @reuniao = params[:reuniao_id]
  end

  def edit
  end

  def create
    @topico = Topico.new(topico_params)
    if @topico.save
      redirect_to @topico, notice: 'Topico was successfully created.'
    else
      render :new
    end
  end

  def update
    if @topico.update(topico_params)
      redirect_to @topico, notice: 'Topico was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @topico.destroy
    redirect_to topicos_url, notice: 'Topico was successfully destroyed.'
  end

  private
    def set_topico
      @topico = Topico.find(params[:id])
    end

    def topico_params
      params.require(:topico).permit(:descricao, :encerrado, :reuniao_id)
    end
end

app/views/topicos/_add.html.erb
<%= form_for(@topico, remote: true) do |f| %>
    <% if @topico.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@topico.errors.count, "error") %> prohibited this topico from being saved:</h2>

          <ul>
            <% @topico.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-sm-8">
        <%= f.text_field :descricao, placeholder: "Digite o tópico aqui...", class: "form-control" %>
      </div>
      <div class="col-sm-4">
        <button type="submit" class="btn btn-primary" value="Salvar">Salvar</button>
      </div>
    </div>

    <%= f.hidden_field :encerrado, value: false %>
    <%= f.hidden_field :reuniao_id, value: @reuniao %>

<% end %>

app/views/topicos/_form.html.erb
<%= form_for(@topico) do |f| %>
  <% if @topico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topico.errors.count, "error") %> prohibited this topico from being saved:</h2>

      <ul>
      <% @topico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :encerrado %><br>
    <%= f.check_box :encerrado %>
  </div>
  <div class="field">
    <%= f.label :reuniao_id %><br>
    <%= f.text_field :reuniao_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topicos/edit.html.erb
<h1>Editing topico</h1>

<%= render 'form' %>

<%= link_to 'Show', @topico %> |
<%= link_to 'Back', topicos_path %>

app/views/topicos/index.html.erb
<h1>Listing topicos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Encerrado</th>
      <th>Reuniao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topicos.each do |topico| %>
      <tr>
        <td><%= topico.descricao %></td>
        <td><%= topico.encerrado %></td>
        <td><%= topico.reuniao %></td>
        <td><%= link_to 'Show', topico %></td>
        <td><%= link_to 'Edit', edit_topico_path(topico) %></td>
        <td><%= link_to 'Destroy', topico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topico', new_topico_path %>

app/views/topicos/new.html.erb
<h1>New topico</h1>

<%= render 'form' %>

<%= link_to 'Back', topicos_path %>

app/views/topicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @topico.descricao %>
</p>

<p>
  <strong>Encerrado:</strong>
  <%= @topico.encerrado %>
</p>

<p>
  <strong>Reuniao:</strong>
  <%= @topico.reuniao %>
</p>

<%= link_to 'Edit', edit_topico_path(@topico) %> |
<%= link_to 'Back', topicos_path %>